# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build Api and push to container registry
  inputs:
        command: buildAndPush
        repository: $(api_image_name)
        dockerfile: NET/Api.Dockerfile
        containerRegistry: DockerHubRepo_api
        tags: latest

- task: Docker@2
  displayName: Build mobile client and push to container registry
  inputs:
        command: buildAndPush
        repository: $(clients_image_name)
        dockerfile: Angular/MobileApp.Dockerfile
        containerRegistry: DockerHubRepo_clients
        tags: latest

- task: Docker@2
  displayName: Build web client and push to container registry
  inputs:
        command: buildAndPush
        repository: $(web_image_name)
        dockerfile: Angular/WebApp.Dockerfile
        containerRegistry: DockerHubRepo_webClient
        tags: latest