---
openapi: 3.0.1
info:
  title: My API
  version: v1
paths:
  "/api/Auth/login":
    post:
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LoginDTO"
          text/json:
            schema:
              "$ref": "#/components/schemas/LoginDTO"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/LoginDTO"
      responses:
        '200':
          description: Success
  "/api/Test/test":
    get:
      tags:
      - Test
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                "$ref": "#/components/schemas/LoginDTO"
            application/json:
              schema:
                "$ref": "#/components/schemas/LoginDTO"
            text/json:
              schema:
                "$ref": "#/components/schemas/LoginDTO"
components:
  schemas:
    LoginDTO:
      type: object
      properties:
        username:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
