#!/bin/sh

echo "{\n\t\"apiBaseUrl\": \"$(printenv API_BASE_URL)\"\n}" > /usr/local/apache2/htdocs/caregiver_app/assets/config.json
echo "{\n\t\"apiBaseUrl\": \"$(printenv API_BASE_URL)\"\n}" > /usr/local/apache2/htdocs/caregiver_app/assets/config.json

# start Apache
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND