version: '3.4' 
services:
  dss_api:
    image: janipe05/dss_api:latest
    depends_on:
      - "local_db"
    restart: always
    ports:
      - "80:80"
    environment:
      DssConnectionString: "Host=local_db;Port=5432;Database=local-db;Username=postgres;Password=postgres;Timeout=0;"
  local_db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "local-db"
     